name: Pre-Commit

on:
    pull_request:
    push:
        branches: [main]

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
            - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 #v5.6.0
              with:
                  python-version: "3.x"
            - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 #v4.2.3
              with:
                  path: ~/.cache/pre-commit
                  key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
            - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 #v4.2.3
              id: apt-cache
              with:
                  path: /var/cache/apt
                  key: apt-${{ runner.os }}-shellcheck-shfmt
            - name: Install shfmt and shellcheck
              if: steps.apt-cache.outputs.cache-hit != 'true'
              run: sudo apt-get update && sudo apt-get install -y shellcheck shfmt
            - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd #v3.0.1
              with:
                  extra_args: --all-files
