name: Versioning

on:
    push:
        branches:
            - main

permissions:
    contents: write
    issues: write
    pull-requests: write

jobs:
    versioning:
        name: Versioning
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
              with:
                  fetch-depth: 0

            - name: Release
              uses: cycjimmy/semantic-release-action@9cc899c47e6841430bbaedb43de1560a568dfd16 #v5.0.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
